name: hijauloka
description: "A new Flutter project."
publish_to: "none"
version: 0.9.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  url_launcher: ^6.1.14
  form_field_validator: ^1.1.0
  google_sign_in: ^6.1.5 # Keep only this version
  google_sign_in_web: ^0.12.0
  flutter_facebook_auth: ^6.0.4
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^8.0.0
  flutter_secure_storage_web: ^1.1.1
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/category-pots.png
    - assets/img/plantcategory.png
    - assets/img/seedscategory.png
    - assets/img/HijauLoklogo.png
    - assets/img/news1.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoicon.png"
